-- Le bootstrap du Super Admin nécessite l'API Auth (création d'utilisateurs).
-- Il est réalisé par le script Node : `node scripts/bootstrap.mjs`
-- (crée / met à jour le compte super-admin). Voir README.
-- Le mode démo a été retiré : les espaces de test se créent via l'inscription normale.
