import type { BackupTableDefinition } from "@/lib/backups/types";

/**
 * Catalogue métier volontairement explicite. Ajouter une table ici est une
 * décision de confidentialité, pas une conséquence automatique du schéma.
 */
export const BACKUP_TABLES: readonly BackupTableDefinition[] = [
  { table: "workspaces", sheet: "Entreprise", title: "Entreprise", description: "Identité, coordonnées et préférences de l’entreprise." },
  { table: "memberships", sheet: "Equipe", title: "Équipe", description: "Membres, rôles et informations professionnelles.", excludedColumns: ["user_id"] },
  { table: "permissions", sheet: "Autorisations", title: "Autorisations", description: "Autorisations accordées aux membres." },
  {
    table: "clients",
    sheet: "Clients",
    title: "Clients",
    description: "Fichier clients et coordonnées.",
    excludedColumns: ["private_code_hash", "private_code_set_at", "portal_token", "access_portal_code", "access_code"],
  },
  { table: "service_series", sheet: "Contrats entretien", title: "Contrats d’entretien", description: "Règles récurrentes et planification future.", excludedColumns: ["pool_id"] },
  { table: "services", sheet: "Entretiens", title: "Historique des entretiens", description: "Entretiens planifiés, réalisés, reportés ou annulés.", excludedColumns: ["pool_id"] },
  { table: "service_financials", sheet: "Revenus entretiens", title: "Revenus des entretiens", description: "Données financières réservées au gérant." },
  { table: "service_tasks", sheet: "Taches entretien", title: "Tâches d’entretien", description: "Listes d’actions rattachées aux entretiens." },
  { table: "service_client_notes", sheet: "Notes clients", title: "Notes clients", description: "Notes transmises depuis le portail client." },
  { table: "contracts", sheet: "Contrats", title: "Contrats", description: "Contrats commerciaux et références documentaires." },
  { table: "invoices", sheet: "Factures", title: "Factures", description: "Factures et montants." },
  { table: "invoice_lines", sheet: "Lignes factures", title: "Lignes de factures", description: "Détail des factures." },
  { table: "documents", sheet: "Documents", title: "Documents", description: "Index des fichiers inclus dans l’archive.", filter: "exclude_pool_documents" },
  { table: "tasks", sheet: "Taches professionnelles", title: "Tâches professionnelles", description: "Tâches partagées ou attribuées, hors to-do personnelles.", filter: "professional_tasks" },
  { table: "team_notes", sheet: "Notes equipe", title: "Notes d’équipe", description: "Notes partagées avec l’équipe." },
  { table: "team_note_reads", sheet: "Lectures notes", title: "Lectures des notes", description: "Accusés de lecture des notes d’équipe." },
  { table: "team_note_executions", sheet: "Executions notes", title: "Exécutions des notes", description: "Actions déclarées comme exécutées." },
  { table: "team_note_comments", sheet: "Commentaires notes", title: "Commentaires des notes", description: "Échanges associés aux notes d’équipe." },
  { table: "community_posts", sheet: "Entre nous", title: "Entre nous", description: "Publications internes de l’entreprise." },
  { table: "community_post_comments", sheet: "Commentaires communaute", title: "Commentaires Entre nous", description: "Commentaires des publications." },
  { table: "community_post_reactions", sheet: "Reactions communaute", title: "Réactions Entre nous", description: "Réactions aux publications." },
  { table: "community_post_media", sheet: "Galerie", title: "Galerie", description: "Index des photos incluses dans l’archive." },
] as const;

export const BACKUP_COLUMN_LABELS: Record<string, string> = {
  id: "Identifiant",
  workspace_id: "Identifiant entreprise",
  company_code: "Code entreprise",
  name: "Nom",
  first_name: "Prénom",
  last_name: "Nom de famille",
  company_name: "Société",
  email: "E-mail",
  phone: "Téléphone",
  address_line1: "Adresse",
  address_line2: "Complément d’adresse",
  postal_code: "Code postal",
  city: "Ville",
  country: "Pays",
  role: "Rôle",
  member_type: "Type de membre",
  job_title: "Poste",
  status: "Statut",
  title: "Titre",
  description: "Description",
  content: "Contenu",
  notes: "Notes",
  report: "Compte rendu",
  code: "Code",
  reference: "Référence",
  service_type: "Type d’entretien",
  kind: "Type",
  scheduled_date: "Date planifiée",
  scheduled_time: "Heure planifiée",
  occurrence_date: "Date d’occurrence",
  starts_on: "Début",
  ends_on: "Fin",
  start_date: "Date de début",
  end_date: "Date de fin",
  due_date: "Échéance",
  issue_date: "Date d’émission",
  created_at: "Créé le",
  updated_at: "Modifié le",
  completed_at: "Terminé le",
  amount: "Montant",
  subtotal: "Sous-total",
  tax_rate: "Taux de TVA",
  tax_amount: "Montant TVA",
  total: "Total",
  currency: "Devise",
  storage_path: "Chemin du fichier",
  original_storage_path: "Chemin de l’original",
  original_name: "Nom du fichier original",
  original_mime_type: "Type du fichier original",
  original_size_bytes: "Taille de l’original (octets)",
  mime_type: "Type de fichier",
  size_bytes: "Taille (octets)",
};

export function columnLabel(column: string): string {
  return BACKUP_COLUMN_LABELS[column] ?? column.replaceAll("_", " ").replace(/^./, (value) => value.toLocaleUpperCase("fr-FR"));
}
